FROM ghcr.io/sarisia/mikanos:latest
RUN git clone https://github.com/uchan-nos/mikanos.git mikanos

# set X11 server address
ENV DISPLAY=:0.0
ENV OS_DIR=/home/vscode/mikanos
ENV EDK=/home/vscode/edk2
ENV IVORY=/workspaces/ivoryOS

